In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
import requests
import pandas as pd
from lxml import etree
from bs4 import BeautifulSoup
import calendar
import csv
import json

In [4]:
months = [i for i in range(1, 9)]
days = [calendar.monthrange(2020, m)[1] for m in months]


months
days

[1, 2, 3, 4, 5, 6, 7, 8]

[31, 29, 31, 30, 31, 30, 31, 31]

In [5]:
def r_get(url, opt=1):
    header = {"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"}

    r = requests.get(url, headers=header)
    r.encoding = 'utf-8'

    if opt == 0:
        return BeautifulSoup(r.text, "lxml")
    else:
        return etree.HTML(r.text)

In [6]:
def filling(num):
    return f"0{str(num)}" if num < 10 else num

In [7]:
data = {}

for i, month in enumerate(months):
    for day in range(1, days[i]+1):
        url = f"https://www.immd.gov.hk/hkt/stat_2020{filling(month)}{filling(day)}.html"

        tree = r_get(url)

        data[f"2020/{filling(month)}/{filling(day)}"] = [int(td.text.replace(",", "").strip()) for td in tree.xpath("/html/body/div/table/tbody/tr[21]/td[@class='hRight'][4]")]

In [8]:
data

{'2020/01/01': [],
 '2020/01/02': [],
 '2020/01/03': [],
 '2020/01/04': [],
 '2020/01/05': [],
 '2020/01/06': [],
 '2020/01/07': [],
 '2020/01/08': [],
 '2020/01/09': [],
 '2020/01/10': [],
 '2020/01/11': [],
 '2020/01/12': [],
 '2020/01/13': [],
 '2020/01/14': [],
 '2020/01/15': [],
 '2020/01/16': [],
 '2020/01/17': [],
 '2020/01/18': [],
 '2020/01/19': [],
 '2020/01/20': [],
 '2020/01/21': [],
 '2020/01/22': [],
 '2020/01/23': [],
 '2020/01/24': [162240],
 '2020/01/25': [135485],
 '2020/01/26': [217065],
 '2020/01/27': [219066],
 '2020/01/28': [223192],
 '2020/01/29': [236350],
 '2020/01/30': [160923],
 '2020/01/31': [140859],
 '2020/02/01': [138264],
 '2020/02/02': [140513],
 '2020/02/03': [131004],
 '2020/02/04': [69812],
 '2020/02/05': [58784],
 '2020/02/06': [82017],
 '2020/02/07': [95982],
 '2020/02/08': [23399],
 '2020/02/09': [29015],
 '2020/02/10': [21777],
 '2020/02/11': [19260],
 '2020/02/12': [18697],
 '2020/02/13': [16521],
 '2020/02/14': [16764],
 '2020/02/15': [19509],
 '2020/02/16': [23393],
 '2020/02/17': [19001],
 '2020/02/18': [17413],
 '2020/02/19': [15658],
 '2020/02/20': [16649],
 '2020/02/21': [17935],
 '2020/02/22': [18771],
 '2020/02/23': [23565],
 '2020/02/24': [19970],
 '2020/02/25': [17832],
 '2020/02/26': [17061],
 '2020/02/27': [16952],
 '2020/02/28': [18448],
 '2020/02/29': [21762],
 '2020/03/01': [25574],
 '2020/03/02': [20284],
 '2020/03/03': [17437],
 '2020/03/04': [16844],
 '2020/03/05': [16695],
 '2020/03/06': [18911],
 '2020/03/07': [19758],
 '2020/03/08': [23908],
 '2020/03/09': [18967],
 '2020/03/10': [17107],
 '2020/03/11': [17657],
 '2020/03/12': [16565],
 '2020/03/13': [18745],
 '2020/03/14': [19282],
 '2020/03/15': [24528],
 '2020/03/16': [21488],
 '2020/03/17': [18686],
 '2020/03/18': [20583],
 '2020/03/19': [13118],
 '2020/03/20': [14858],
 '2020/03/21': [13494],
 '2020/03/22': [12797],
 '2020/03/23': [11652],
 '2020/03/24': [14783],
 '2020/03/25': [5297],
 '2020/03/26': [4458],
 '2020/03/27': [4033],
 '2020/03/28': [4662],
 '2020/03/29': [3584],
 '2020/03/30': [2933],
 '2020/03/31': [2495],
 '2020/04/01': [2146],
 '2020/04/02': [1445],
 '2020/04/03': [1652],
 '2020/04/04': [1302],
 '2020/04/05': [1649],
 '2020/04/06': [1465],
 '2020/04/07': [992],
 '2020/04/08': [1576],
 '2020/04/09': [1167],
 '2020/04/10': [1646],
 '2020/04/11': [960],
 '2020/04/12': [1181],
 '2020/04/13': [1082],
 '2020/04/14': [1146],
 '2020/04/15': [1244],
 '2020/04/16': [1056],
 '2020/04/17': [1476],
 '2020/04/18': [980],
 '2020/04/19': [1131],
 '2020/04/20': [1272],
 '2020/04/21': [882],
 '2020/04/22': [1090],
 '2020/04/23': [696],
 '2020/04/24': [1316],
 '2020/04/25': [932],
 '2020/04/26': [955],
 '2020/04/27': [984],
 '2020/04/28': [944],
 '2020/04/29': [1386],
 '2020/04/30': [1788],
 '2020/05/01': [1528],
 '2020/05/02': [1159],
 '2020/05/03': [1647],
 '2020/05/04': [1577],
 '2020/05/05': [1106],
 '2020/05/06': [1410],
 '2020/05/07': [1231],
 '2020/05/08': [2652],
 '2020/05/09': [2001],
 '2020/05/10': [3096],
 '2020/05/11': [3078],
 '2020/05/12': [2778],
 '2020/05/13': [2030],
 '2020/05/14': [1670],
 '2020/05/15': [2115],
 '2020/05/16': [2260],
 '2020/05/17': [2413],
 '2020/05/18': [2222],
 '2020/05/19': [1494],
 '2020/05/20': [2064],
 '2020/05/21': [1884],
 '2020/05/22': [2496],
 '2020/05/23': [2857],
 '2020/05/24': [4147],
 '2020/05/25': [2570],
 '2020/05/26': [1605],
 '2020/05/27': [1380],
 '2020/05/28': [1572],
 '2020/05/29': [1848],
 '2020/05/30': [1851],
 '2020/05/31': [2581],
 '2020/06/01': [2095],
 '2020/06/02': [1985],
 '2020/06/03': [2419],
 '2020/06/04': [2672],
 '2020/06/05': [2873],
 '2020/06/06': [2357],
 '2020/06/07': [3775],
 '2020/06/08': [3465],
 '2020/06/09': [2451],
 '2020/06/10': [2516],
 '2020/06/11': [1945],
 '2020/06/12': [2378],
 '2020/06/13': [1995],
 '2020/06/14': [1874],
 '2020/06/15': [3750],
 '2020/06/16': [3589],
 '2020/06/17': [3480],
 '2020/06/18': [3264],
 '2020/06/19': [3447],
 '2020/06/20': [2000],
 '2020/06/21': [2295],
 '2020/06/22': [3242],
 '2020/06/23': [3692],
 '2020/06/24': [3278],
 '2020/06/25': [1518],
 '2020/06/26': [3384],
 '2020/06/27': [1744],
 '2020/06/28': [1773],
 '2020/06/29': [2891],
 '2020/06/30': [3690],
 '2020/07/01': [1473],
 '2020/07/02': [3543],
 '2020/07/03': [3711],
 '2020/07/04': [2117],
 '2020/07/05': [2562],
 '2020/07/06': [3608],
 '2020/07/07': [3839],
 '2020/07/08': [3974],
 '2020/07/09': [3045],
 '2020/07/10': [3624],
 '2020/07/11': [2326],
 '2020/07/12': [2229],
 '2020/07/13': [2105],
 '2020/07/14': [1748],
 '2020/07/15': [2107],
 '2020/07/16': [1453],
 '2020/07/17': [1931],
 '2020/07/18': [1367],
 '2020/07/19': [1517],
 '2020/07/20': [1299],
 '2020/07/21': [1254],
 '2020/07/22': [1570],
 '2020/07/23': [873],
 '2020/07/24': [1479],
 '2020/07/25': [992],
 '2020/07/26': [1154],
 '2020/07/27': [902],
 '2020/07/28': [1282],
 '2020/07/29': [734],
 '2020/07/30': [663],
 '2020/07/31': [1099],
 '2020/08/01': [1025],
 '2020/08/02': [1137],
 '2020/08/03': [934],
 '2020/08/04': [1114],
 '2020/08/05': [1101],
 '2020/08/06': [830],
 '2020/08/07': [],
 '2020/08/08': [],
 '2020/08/09': [],
 '2020/08/10': [],
 '2020/08/11': [],
 '2020/08/12': [],
 '2020/08/13': [],
 '2020/08/14': [],
 '2020/08/15': [],
 '2020/08/16': [],
 '2020/08/17': [],
 '2020/08/18': [],
 '2020/08/19': [],
 '2020/08/20': [],
 '2020/08/21': [],
 '2020/08/22': [],
 '2020/08/23': [],
 '2020/08/24': [],
 '2020/08/25': [],
 '2020/08/26': [],
 '2020/08/27': [],
 '2020/08/28': [],
 '2020/08/29': [],
 '2020/08/30': [],
 '2020/08/31': []}

In [9]:
df=pd.DataFrame.from_dict(data, orient='index').dropna()
df = df.reset_index().rename(columns={0:'Entries','index':'Date'})
df.to_csv('Entry.csv',index=0) 
df

           Date   Entries
0    2020/01/24  162240.0
1    2020/01/25  135485.0
2    2020/01/26  217065.0
3    2020/01/27  219066.0
4    2020/01/28  223192.0
..          ...       ...
191  2020/08/02    1137.0
192  2020/08/03     934.0
193  2020/08/04    1114.0
194  2020/08/05    1101.0
195  2020/08/06     830.0

[196 rows x 2 columns]